# Generated by Django 6.0 on 2026-01-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=1949),
            preserve_default=False,
        ),
    ]
